# Server Port (Dynamic port for Cloud deployment, default 8080)
server.port=${PORT:8080}

# Neon Cloud Database
spring.datasource.url=jdbc:postgresql://ep-aged-salad-b5b81n6b-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sAJZ4NW0vMOf
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upstash Cloud Redis Configuration
spring.data.redis.host=excited-oriole-198695.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAwgnAAIgcDE4NWJiNGZjMzYwN2E0ODJiOTQzYzg4MTUwMWNiNDIzZg
spring.data.redis.ssl.enabled=true

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000